package p004o;

/* renamed from: o.nj */
enum C0583nj {
    ATTACK,
    ITEMPICKUP,
    SIT,
    STAND,
    ATTACK_NOMOTION,
    SPLASH,
    SKILL,
    ATTACK_REPEAT,
    ATTACK_MULTIPLE,
    ATTACK_MULTIPLE_NOMOTION,
    ATTACK_CRITICAL,
    ATTACK_LUCKY,
    TOUCHSKILL,
    MULTI_HIT_CRITICAL
}
